<?php

$modversion['name'] = _PRICELIST_NAME;
$modversion['version'] = '2.0+ZIP';
$modversion['description'] = _PRICELIST_DESC;
$modversion['author'] = 'Anatol Leskovski (modifed by ArTeMkA nedam@mail.ru)';
$modversion['credits'] = 'Photoman Design Group';
$modversion['help'] = '';
$modversion['license'] = 'GPL';
$modversion['official'] = 0;
$modversion['image'] = 'images/price_logo.gif';
$modversion['dirname'] = 'pricelist';
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'pricelist_dealers';
$modversion['tables'][1] = 'pricelist_categories';
$modversion['tables'][2] = 'pricelist_items';
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
// Blocks
//$modversion['blocks'][1]['file'] = "pricelist.php";
//$modversion['blocks'][1]['name'] = _PRICELIST_BNAME;
//$modversion['blocks'][1]['description'] = _PRICELIST_DESC;
//$modversion['blocks'][1]['show_func'] = "b_pricelist_show";
//$modversion['blocks'][1]['edit_func'] = "b_pricelist_edit";
//$modversion['blocks'][1]['options'] = "1";
// Menu
$modversion['hasMain'] = 1;
